import React from "react";

import Head from "next/head";
import Image from "next/image";
import style from "./index.module.scss";
import Layout from "@/section/layout";
import { Col, Container, Row } from "react-bootstrap";
import { FaArrowRight, FaStar } from "react-icons/fa";
import heroImage from "@/assets/front/images/hero-2.webp";
import bannerImage from "@/assets/front/images/ban-slider/ban-1.jpg";
import Link from "next/link";
import FeaturesSection from "@/components/featuresSection";
import CounterSection from "@/components/counter";
import OutdoorKitchens from "@/components/outdoorKitchen";
import ModelConfiguratorBanner from "@/components/modelConfiguratorBanner";
import ComparisonTable from "@/components/comparisonTable";
import YourGarden from "@/components/yourGarden";
import ExteriorColours from "@/components/exteriorColours";
import StainlessSteel from "@/components/stainlessSteel";
import InteriorFinishesBanner from "@/components/interiorFinishesBanner";
import Testimonials from "@/components/testimonials";
import CraftedBy from "@/components/craftedBy";
import Faqs from "@/components/faqs";
import Cta from "@/components/cta";
import TitleHeader from "@/components/titleHeader";

import bannerBg from "@/assets/front/images/home-banner.avif";

import { TiArrowRightOutline } from "react-icons/ti";

export const homeFaqs = [
  {
    question: "How long does delivery take?",
    answer:
      "From order confirmation, delivery and installation typically take up to 16 weeks. In quieter periods this can be closer to 14 weeks, depending on production schedules and your chosen specification. We’ll always confirm lead times before securing your order.",
  },
  {
    question: "What warranty is included?",
    answer:
      "All BBQ Pods come with a 10-year structural warranty and a 2-year warranty on appliances, as detailed in our brochure. This covers normal residential use and manufacturing defects.",
  },
  {
    question: "What is required for installation?",
    answer:
      "The pod must be installed on solid, level ground capable of supporting its weight. An external electrical socket is required, along with a water supply and waste connection if a sink is included. Due to the weight of the units, suitable access for delivery and crane placement is also necessary.",
  },
  {
    question: "Can the BBQ Pod be used year-round?",
    answer:
      "Yes. BBQ Pods are designed for outdoor living in the Spanish climate. When closed, the interior remains clean and protected from dust and rain. When open, integrated shading and lighting allow comfortable outdoor cooking throughout the year.",
  },
  {
    question: "How do I choose the right model?",
    answer:
      "The right model depends on your available space, how you plan to use the pod, and your preferred features. We’re happy to advise and can prepare a visualisation to help you choose with confidence.",
  },
  {
    question: "What maintenance is required?",
    answer:
      "Maintenance is simple and minimal. Regular cleaning of cooking surfaces and occasional care of stainless-steel areas will keep your BBQ Pod performing and looking its best.",
  },
  {
    question: "Can I customise the pod after ordering?",
    answer:
      "All major customisation is completed before production begins. Once an order is confirmed, changes are limited, so we’ll guide you through all options carefully to ensure everything is right from the start.",
  },
  {
    question: "Need Further Information?",
    answer:
      "Speak with our team for personalised advice on selecting the right BBQ Pod for your home.",
  },
];

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section
          className={style.banner}
          style={{
            backgroundImage: `url(${bannerBg.src})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
        >
          <Container>
            <Row className="align-items-center">
              {/* LEFT CONTENT */}
              <Col md={12}>
                <div className={style.bannerContent}>
                  {/* <div
                    className={style.nationwide}
                    data-aos="fade-up"
                    data-aos-anchor-placement="bottom-center"
                    data-aos-easing="ease-out-cubic"
                    data-aos-duration="1500"
                    data-aos-once="true"
                  >
                    <i className="fa-regular fa-circle-check" /> UK Nationwide
                  </div> */}

                  <h1
                    data-aos="fade-right"
                    data-aos-duration="2000"
                    data-aos-once="true"
                  >
                    Outdoor cooking, Redefined.
                    {/* Luxury Outdoor Kitchen Pods */}
                  </h1>

                  <h3
                    data-aos="fade-right"
                    data-aos-duration="2500"
                    data-aos-once="true"
                  >
                    Luxury Outdoor Kitchen Pods
                    {/* Grill. Gather. Enjoy. */}
                  </h3>

                  {/* <p
                    data-aos="fade-right"
                    data-aos-duration="3000"
                    data-aos-once="true"
                    dangerouslySetInnerHTML={{
                      __html: `Premium Outdoor Kitchens Delivered from the UK — Built to Last
                  a Lifetime.`,
                    }}
                  ></p> */}

                  <div className={style.actions}>
                    <Link
                      href={"/products"}
                      className={style.exploreBtn}
                      data-aos="zoom-out"
                      data-aos-duration="2500"
                      data-aos-once="true"
                    >
                      Explore Products <TiArrowRightOutline className="ms-1" />
                    </Link>
                    {/* <ul>
                      <li>
                        <Link
                          href={"/products"}
                          className={style.exploreBtn}
                          data-aos="zoom-out"
                          data-aos-duration="2500"
                          data-aos-once="true"
                        >
                          Explore Products
                        </Link>
                      </li>
                      <li>
                        <Link
                          href={""}
                          className={style.quoteBtn}
                          data-aos="zoom-out"
                          data-aos-duration="2500"
                          data-aos-once="true"
                        >
                          Explore Models
                        </Link>
                      </li>
                    </ul> */}
                  </div>

                  {/* <div className={style.features}>
                    <ul>
                      <li>
                        <i className="fa-solid fa-medal" /> Quality Assured
                      </li>
                      <li>
                        <i className="fa-solid fa-truck-fast" /> UK-Wide
                        Delivery
                      </li>
                      <li>
                        <i className="fa-solid fa-umbrella-beach" /> Fully
                        Assembled
                      </li>
                    </ul>
                  </div> */}
                </div>
              </Col>

              {/* RIGHT IMAGE */}
              {/* <Col md={4}>
                <div
                  className={style.bannerImage}
                  data-aos="flip-left"
                  data-aos-easing="ease-out-cubic"
                  data-aos-duration="2000"
                  data-aos-once="true"
                >
                  <Image
                    src={bannerImage}
                    alt="Landscape"
                    width={600}
                    height={450}
                    className={style.banImgmage}
                    priority
                  />

                  <ul className={style.stats}>
                    <li>
                      <strong>A+</strong>
                      <span>Premium Quality</span>
                    </li>
                    <li>
                      <strong>100%</strong>
                      <span>Assembled</span>
                    </li>
                    <li>
                      <strong>Uk</strong>
                      <span>Wide Delivery</span>
                    </li>
                  </ul>
                </div>
              </Col> */}
            </Row>
          </Container>
        </section>
        <FeaturesSection />
        <CounterSection />
        <OutdoorKitchens />
        {/* <ModelConfiguratorBanner
          title="Find the Right BBQ Pod for Your Space"
          description="Compare models, explore configurations and visualise your outdoor kitchen before receiving a personalised quote."
          rightButton="Compare Models"
          leftButtonWrap={false}
          // rightButtonWrap={true}
        /> */}
        <ComparisonTable />
        <YourGarden
          title="Discover the BBQ Pod Spain Range"
          description="Receive our full brochure by email and explore all models, features and finishes at your own pace."
          backgroundImage={heroImage}
          badges={[
            {
              icon: <FaArrowRight />,
              text: "Full model range & specifications",
            },
            { icon: <FaArrowRight />, text: "Pricing guidance" },
            {
              icon: <FaArrowRight />,
              text: "Designed for the Spanish lifestyle",
            },
          ]}
          primaryButton={{
            label: "Send Me the Brochure",
            href: "",
          }}
          secondaryButton={{
            label: "Try the Configurator",
            href: "",
          }}
          footerText="Join 100+ satisfied UK families who transformed their gardens with BBQ Pods"
        />
        <ExteriorColours />
        {/* <StainlessSteel /> */}
        {/* <InteriorFinishesBanner /> */}
        <Testimonials />
        {/* <CraftedBy /> */}
        <section className={style.faqs}>
          <TitleHeader
            whyChoose="Frequently Asked Questions"
            title="Helpful Information"
            subtitle="Details on our BBQ Pods, delivery and installation, all in one place"
          />
          {/* <Faqs /> */}
          <Faqs faqs={homeFaqs} />
        </section>
        <Cta />
      </Layout>
    </>
  );
};

export default Home;
