import React from "react";

import Head from "next/head";
import Image from "next/image";
import style from "./index.module.scss";
import Layout from "@/section/layout";
import { Col, Container, Row } from "react-bootstrap";
import { FaArrowRight, FaStar } from "react-icons/fa";
import heroImage from "@/assets/front/images/hero-2.webp";
import bannerImage from "@/assets/front/images/ban-slider/ban-1.jpg";
import Link from "next/link";
import FeaturesSection from "@/components/featuresSection";
import CounterSection from "@/components/counter";
import OutdoorKitchens from "@/components/outdoorKitchen";
import ModelConfiguratorBanner from "@/components/modelConfiguratorBanner";
import ComparisonTable from "@/components/comparisonTable";
import YourGarden from "@/components/yourGarden";
import ExteriorColours from "@/components/exteriorColours";
import StainlessSteel from "@/components/stainlessSteel";
import InteriorFinishesBanner from "@/components/interiorFinishesBanner";
import Testimonials from "@/components/testimonials";
import CraftedBy from "@/components/craftedBy";
import Faqs from "@/components/faqs";
import Cta from "@/components/cta";
import TitleHeader from "@/components/titleHeader";

export const homeFaqs = [
  {
    question: "How long is the shipping time?",
    answer:
      "Shipping typically takes 4-8 weeks depending on the manufacturer, customization level, and location. For example, prefabricated models may ship in 4-6 weeks, while international freight can add 30-45 days.",
  },
  {
    question: "Do I need planning permission for a BBQ pod?",
    answer:
      "In the UK, most BBQ pods fall under permitted development rights and do not require planning permission if they are under 4 meters in height, not a permanent structure, and meet size limits (e.g., covering less than 50% of your garden). Always check with your local authority, especially in conservation areas.",
  },
  {
    question: "What warranty coverage is included?",
    answer:
      "Warranties vary by brand but generally include 2-5 years on the structure and parts, with 1-5 years on appliances like grills and refrigerators. Exclusions often apply for misuse or lack of maintenance. Check the manufacturer's documentation for details.",
  },
  {
    question: "Can I use the pod year-round in British weather?",
    answer:
      "Yes, most BBQ pods are designed for year-round use with weatherproof materials like 304 stainless steel, insulation, and features like motorized awnings. They can withstand rain, wind, and cold, allowing outdoor cooking even in winter.",
  },
  {
    question: "What utilities do I need for installation?",
    answer:
      "Basic requirements include a level concrete base, 240V electrical supply for lights and appliances, gas (natural or propane) for the grill, and water/drainage if including a sink. Professional installation is recommended for safety.",
  },
  {
    question: "How do I choose the right model for my garden?",
    answer:
      "Consider your garden size, desired features (e.g., grill size, storage, refrigeration), budget, and customization options like colors or appliances. Measure your space and think about usage—compact models for small gardens, larger ones for entertaining.",
  },
  {
    question: "What ongoing maintenance is required?",
    answer:
      "Regular cleaning of grates and burners after each use, deep cleaning every 3 months (scrub interior, check for rust), and annual inspections of gas lines and electrical components. Use mild soap and avoid harsh chemicals to preserve the finish.",
  },
  {
    question: "Can I customise the pod after purchase?",
    answer:
      "Major customizations like colors and finishes are typically done at purchase, but you can often add or upgrade accessories, appliances, storage, or lighting post-purchase. Some brands offer modular designs for easy modifications.",
  },
];

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className={style.banner}>
          <Container>
            <Row className="align-items-center">
              {/* LEFT CONTENT */}
              <Col md={7}>
                <div className={style.bannerContent}>
                  <div
                    className={style.nationwide}
                    data-aos="fade-up"
                    data-aos-anchor-placement="bottom-center"
                    data-aos-easing="ease-out-cubic"
                    data-aos-duration="1500"
                    data-aos-once="true"
                  >
                    <i className="fa-regular fa-circle-check" /> UK Nationwide
                  </div>

                  <h1
                    data-aos="fade-right"
                    data-aos-duration="2000"
                    data-aos-once="true"
                  >
                    Luxury Outdoor Kitchen Pods
                  </h1>

                  <h3
                    data-aos="fade-right"
                    data-aos-duration="2500"
                    data-aos-once="true"
                  >
                    Grill. Gather. Enjoy.
                  </h3>

                  <p
                    data-aos="fade-right"
                    data-aos-duration="3000"
                    data-aos-once="true"
                    dangerouslySetInnerHTML={{
                      __html: `Premium Outdoor Kitchens Delivered from the UK — Built to Last
                  a Lifetime.`,
                    }}
                  ></p>

                  <div className={style.actions}>
                    <ul>
                      <li>
                        <Link
                          href={""}
                          className={style.callBtn}
                          data-aos="zoom-out"
                          data-aos-duration="2500"
                          data-aos-once="true"
                        >
                          Get My Personalised Quote
                        </Link>
                      </li>
                      <li>
                        <Link
                          href={""}
                          className={style.quoteBtn}
                          data-aos="zoom-out"
                          data-aos-duration="2500"
                          data-aos-once="true"
                        >
                          Explore Models
                        </Link>
                      </li>
                    </ul>
                  </div>

                  <div className={style.features}>
                    <ul>
                      <li>
                        <i className="fa-solid fa-medal" /> Quality Assured
                      </li>
                      <li>
                        <i className="fa-solid fa-truck-fast" /> UK-Wide
                        Delivery
                      </li>
                      <li>
                        <i className="fa-solid fa-umbrella-beach" /> Fully
                        Assembled
                      </li>
                    </ul>
                  </div>
                </div>
              </Col>

              {/* RIGHT IMAGE */}
              <Col md={5}>
                <div
                  className={style.bannerImage}
                  data-aos="flip-left"
                  data-aos-easing="ease-out-cubic"
                  data-aos-duration="2000"
                  data-aos-once="true"
                >
                  <Image
                    src={bannerImage}
                    alt="Landscape"
                    width={600}
                    height={450}
                    className={style.banImgmage}
                    priority
                  />

                  <ul className={style.stats}>
                    <li>
                      <strong>A+</strong>
                      <span>Premium Quality</span>
                    </li>
                    <li>
                      <strong>100%</strong>
                      <span>Assembled</span>
                    </li>
                    <li>
                      <strong>Uk</strong>
                      <span>Wide Delivery</span>
                    </li>
                  </ul>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <FeaturesSection />
        <CounterSection />
        <OutdoorKitchens />
        <ModelConfiguratorBanner
          title="Not Sure Which Model Is Right for You?"
          description="Use our interactive configurator to explore features, compare models, and visualise your perfect outdoor kitchen. Get a personalised quote in minutes."
          leftButton="Try Configurator"
          rightButton="Compare All Models"
        />
        <ComparisonTable />
        <YourGarden
          title="Ready to Transform Your Garden?"
          description="Get a personalised quote in under 2 minutes — no obligation from our expert team."
          backgroundImage={heroImage}
          badges={[
            { icon: <FaArrowRight />, text: "2-Minute Quote Process" },
            { icon: <FaStar />, text: "No Obligation Quote" },
          ]}
          primaryButton={{
            label: "Get My Personalised Quote",
            href: "",
          }}
          secondaryButton={{
            label: "Try the Configurator",
            href: "",
          }}
          footerText="Join 100+ satisfied UK families who transformed their gardens with BBQ Pods"
        />
        ;
        <ExteriorColours />
        <StainlessSteel />
        <InteriorFinishesBanner />
        <Testimonials />
        <CraftedBy />
        <section className={style.faqs}>
          <TitleHeader
            whyChoose="FREQUENTLY ASKED QUESTIONS"
            title="Got Questions?"
            subtitle="Everything you need to know about BBQ pods, delivery, and installation."
          />
          {/* <Faqs /> */}
          <Faqs faqs={homeFaqs} />
        </section>
        <Cta />
      </Layout>
    </>
  );
};

export default Home;
