import React from "react";

import Head from "next/head";
import Image from "next/image";
import style from "./index.module.scss";
import Layout from "@/section/layout";
import { Col, Container, Row } from "react-bootstrap";
import bannerImage from "@/assets/front/images/ban-slider/ban-1.jpg";
import Link from "next/link";
import FeaturesSection from "@/components/featuresSection";
import CounterSection from "@/components/counter";
import OutdoorKitchens from "@/components/outdoorKitchen";
import ModelConfiguratorBanner from "@/components/modelConfiguratorBanner";
import ComparisonTable from "@/components/comparisonTable";
import YourGarden from "@/components/yourGarden";
import ExteriorColours from "@/components/exteriorColours";
import StainlessSteel from "@/components/stainlessSteel";
import InteriorFinishesBanner from "@/components/interiorFinishesBanner";
import Testimonials from "@/components/testimonials";
import CraftedBy from "@/components/craftedBy";
import Faqs from "@/components/faqs";
import Cta from "@/components/cta";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className={style.banner}>
          <Container>
            <Row className="align-items-center">
              {/* LEFT CONTENT */}
              <Col md={7} className={style.bannerContent}>
                <div
                  className={style.nationwide}
                  data-aos="fade-up"
                  data-aos-anchor-placement="bottom-center"
                  data-aos-easing="ease-out-cubic"
                  data-aos-duration="1500"
                  data-aos-once="true"
                >
                  <i className="fa-regular fa-circle-check" /> UK Nationwide
                </div>

                <h1
                  data-aos="fade-right"
                  data-aos-duration="2000"
                  data-aos-once="true"
                >
                  Luxury Outdoor Kitchen Pods
                </h1>

                <h3
                  data-aos="fade-right"
                  data-aos-duration="2500"
                  data-aos-once="true"
                >
                  Grill. Gather. Enjoy.
                </h3>

                <p
                  data-aos="fade-right"
                  data-aos-duration="3000"
                  data-aos-once="true"
                  dangerouslySetInnerHTML={{
                    __html: `Premium Outdoor Kitchens Delivered from the UK — Built to Last
                  a Lifetime.`,
                  }}
                ></p>

                <div className={style.actions}>
                  <Link
                    href={""}
                    className={style.callBtn}
                    data-aos="zoom-out"
                    data-aos-duration="2500"
                    data-aos-once="true"
                  >
                    Get My Personalised Quote
                  </Link>

                  <Link
                    href={""}
                    className={style.quoteBtn}
                    data-aos="zoom-out"
                    data-aos-duration="2500"
                    data-aos-once="true"
                  >
                    Explore Models
                  </Link>
                </div>

                <div className={style.features}>
                  <ul>
                    <li>
                      <i className="fa-solid fa-medal" /> Quality Assured
                    </li>
                    <li>
                      <i className="fa-solid fa-truck-fast" /> UK-Wide Delivery
                    </li>
                    <li>
                      <i className="fa-solid fa-umbrella-beach" /> Fully
                      Assembled
                    </li>
                  </ul>
                </div>
              </Col>

              {/* RIGHT IMAGE */}
              <Col md={5}>
                <div
                  className={style.bannerImage}
                  data-aos="flip-left"
                  data-aos-easing="ease-out-cubic"
                  data-aos-duration="2000"
                  data-aos-once="true"
                >
                  <Image
                    src={bannerImage}
                    alt="Landscape"
                    width={600}
                    height={450}
                    className={style.banImgmage}
                    priority
                  />

                  <ul className={style.stats}>
                    <li>
                      <strong>A+</strong>
                      <span>Premium Quality</span>
                    </li>
                    <li>
                      <strong>100%</strong>
                      <span>Assembled</span>
                    </li>
                    <li>
                      <strong>Uk</strong>
                      <span>Wide Delivery</span>
                    </li>
                  </ul>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <FeaturesSection />
        <CounterSection />
        <OutdoorKitchens />
        <ModelConfiguratorBanner />
        <ComparisonTable />
        <YourGarden />
        <ExteriorColours />
        <StainlessSteel />
        <InteriorFinishesBanner />
        <Testimonials />
        <CraftedBy />
        <Faqs />
        <Cta />
      </Layout>
    </>
  );
};

export default Home;
